/**
 * Phase 12.7.x — Episode package zip
 *
 * Replaces the old ffmpeg concat path. The platform's role ends at
 * generating per-panel videos; final cutting happens in CapCut/剪映 on
 * the user's machine. So instead of stitching 17×1080P videos into one
 * mp4 (which pegs both vCPUs for ~6 minutes and stalls BullMQ), we
 * package every panel video + storyboard image + dialogue script into
 * one zip and hand the user a download link.
 *
 * Resource profile vs. ffmpeg:
 *   - CPU: <5% (archiver is I/O bound, not encoder bound)
 *   - Time: ~30-60s for 17 panels (download + zip + upload)
 *   - Memory: peak ~600MB (full zip buffered before upload)
 *   - Heartbeat: 90s default is comfortably enough
 *
 * Output zip layout:
 *   episode-{id}.zip
 *   ├── videos/01-{slug}.mp4 ... 17-{slug}.mp4   (in panel order)
 *   ├── images/01-{slug}.jpg ... 17-{slug}.jpg   (storyboard refs)
 *   ├── script.txt                                (dialogue + camera notes)
 *   └── README.txt                                (import-to-CapCut guide)
 *
 * The output key is written to NovelPromotionEpisode.stitchedVideoUrl —
 * the column name is preserved for backward compat; semantically it now
 * holds a zip key, not an mp4 key. Frontend treats it as a download URL.
 */
import path from 'path'
import fs from 'fs'
import os from 'os'
import archiver from 'archiver'
import type { Job } from 'bullmq'
import { prisma } from '@/lib/prisma'
import type { TaskJobData } from '@/lib/task/types'
import { reportTaskProgress } from '../shared'
import { assertTaskActive, toSignedUrlIfCos } from '../utils'
import { uploadToCOS, generateUniqueKey } from '@/lib/cos'
import { logWarn } from '@/lib/logging/core'

interface PackagePayload {
  episodeId?: string
}

interface PanelForZip {
  id: string
  panelIndex: number
  description: string | null
  imageUrl: string | null
  videoUrl: string | null
  cameraMove: string | null
  shotType: string | null
}

interface DialogueLine {
  panelId: string | null
  panelIndex: number | null
  speaker: string
  content: string
  lineIndex: number
}

const FETCH_TIMEOUT_MS = 60_000

function slugifyForFilename(input: string | null, fallback: string): string {
  const base = (input ?? '').slice(0, 30).replace(/[\\/:*?"<>|\s]+/g, '_').replace(/^_+|_+$/g, '')
  return base.length > 0 ? base : fallback
}

async function fetchToBuffer(url: string): Promise<Buffer> {
  const res = await fetch(url, { signal: AbortSignal.timeout(FETCH_TIMEOUT_MS) })
  if (!res.ok) {
    throw new Error(`HTTP ${res.status} fetching ${url.slice(0, 80)}`)
  }
  return Buffer.from(await res.arrayBuffer())
}

function buildScriptText(panels: PanelForZip[], dialogueByPanelId: Map<string, DialogueLine[]>): string {
  const lines: string[] = ['EPISODE SCRIPT', '', '']
  for (const panel of panels) {
    const indexStr = String(panel.panelIndex).padStart(2, '0')
    lines.push(`--- Panel ${indexStr} ---`)
    if (panel.shotType) lines.push(`Shot: ${panel.shotType}`)
    if (panel.cameraMove) lines.push(`Camera: ${panel.cameraMove}`)
    if (panel.description) lines.push(`Scene: ${panel.description}`)
    const dialogues = dialogueByPanelId.get(panel.id) ?? []
    if (dialogues.length > 0) {
      lines.push('')
      for (const d of dialogues) {
        lines.push(`  ${d.speaker}: ${d.content}`)
      }
    }
    lines.push('', '')
  }
  return lines.join('\n')
}

function buildReadmeText(panelCount: number, multiShotCount: number): string {
  const parts: string[] = []
  if (panelCount > 0) parts.push(`${panelCount} per-panel videos`)
  if (multiShotCount > 0) parts.push(`${multiShotCount} multi-shot group videos`)
  const summary = parts.join(' + ') || 'no videos'
  const lines = [
    'KuiperAI Episode Package',
    '========================',
    '',
    `This zip contains ${summary} plus storyboard images and a dialogue script.`,
    '',
    'Folder layout:',
  ]
  if (panelCount > 0) {
    lines.push('  videos/      — per-panel mp4, named in scene order (01, 02, ...)')
  }
  if (multiShotCount > 0) {
    lines.push('  multi-shot/  — group-level Kling 3.0-Omni multi-shot mp4 (~5-15s each)')
  }
  lines.push(
    '  images/      — storyboard reference images for each panel',
    '  script.txt   — dialogue + camera notes per panel',
    '',
    'Import workflow (CapCut / 剪映):',
    '  1. Drag the entire videos/ and/or multi-shot/ folder into your project.',
    '  2. Files are pre-numbered, so they sort correctly on the timeline.',
    '  3. Use script.txt as a reference for cuts, captions, and voiceover.',
    '',
    'Generated by KuiperAI.',
    '',
  )
  return lines.join('\n')
}

export async function handleEpisodePackageZipTask(job: Job<TaskJobData>) {
  const payload = (job.data.payload || {}) as PackagePayload
  const episodeId = typeof payload.episodeId === 'string' ? payload.episodeId : ''
  if (!episodeId) {
    throw new Error('EPISODE_PACKAGE_ZIP: missing episodeId in payload')
  }

  await reportTaskProgress(job, 5, { stage: 'load_panels' })
  await assertTaskActive(job, 'load_panels')

  const episode = await prisma.novelPromotionEpisode.findUnique({
    where: { id: episodeId },
    include: {
      storyboards: {
        include: {
          panels: { orderBy: { panelIndex: 'asc' } },
        },
        orderBy: { createdAt: 'asc' },
      },
      voiceLines: { orderBy: { lineIndex: 'asc' } },
    },
  })
  if (!episode) {
    throw new Error(`EPISODE_PACKAGE_ZIP: episode not found: ${episodeId}`)
  }

  const allPanels: PanelForZip[] = episode.storyboards.flatMap((sb) =>
    sb.panels.map((p) => ({
      id: p.id,
      panelIndex: p.panelIndex,
      description: p.description,
      imageUrl: p.imageUrl,
      videoUrl: p.videoUrl,
      cameraMove: p.cameraMove,
      shotType: p.shotType,
    })),
  )
  const panelsWithVideo = allPanels.filter((p) => Boolean(p.videoUrl))

  // 2026-05-02 — multi-shot B-path emits one video per group, not per
  // panel; the URL is on the most recent completed video_multi_shot
  // task's result, not on panel.videoUrl. Without this branch, episodes
  // generated through the new path packaged as empty zips and the API
  // route returned NO_PANEL_VIDEOS even though every group had a
  // playable mp4 in COS. Pull each group's latest task and build a
  // groupId → mp4 map so the zip includes both single-shot panel
  // videos AND multi-shot group videos when both exist.
  type GroupVideo = {
    groupOrder: number  // 1-indexed across the episode in storyboard / first-panel order
    storyboardOrder: number
    firstPanelIndex: number
    /**
     * 2026-05-03 — a group can produce multiple clips when its dialogue
     * exceeds Kling Omni's 15s per-call cap. Each clip is a complete
     * mp4; the user stitches them in their NLE. Single-clip groups
     * still ship as length-1 arrays so the loop below stays uniform.
     */
    cosKeys: string[]
    cameraNote: string | null
  }
  const groupVideos: GroupVideo[] = []
  {
    type GroupSig = { storyboardOrder: number; firstPanelIndex: number; storyboardId: string; groupId: string }
    const groupSigs: GroupSig[] = []
    const seenGroupKeys = new Set<string>()
    episode.storyboards.forEach((sb, sbIdx) => {
      const panelsByGroup = new Map<string, number[]>()
      for (const p of sb.panels) {
        if (!p.multiShotGroupId) continue
        const arr = panelsByGroup.get(p.multiShotGroupId) ?? []
        arr.push(p.panelIndex)
        panelsByGroup.set(p.multiShotGroupId, arr)
      }
      for (const [groupId, indices] of panelsByGroup.entries()) {
        const key = `${sb.id}:${groupId}`
        if (seenGroupKeys.has(key)) continue
        seenGroupKeys.add(key)
        groupSigs.push({
          storyboardOrder: sbIdx,
          firstPanelIndex: Math.min(...indices),
          storyboardId: sb.id,
          groupId,
        })
      }
    })
    groupSigs.sort((a, b) =>
      a.storyboardOrder - b.storyboardOrder || a.firstPanelIndex - b.firstPanelIndex,
    )

    if (groupSigs.length > 0) {
      const completedTasks = await prisma.task.findMany({
        where: {
          episodeId: episode.id,
          type: 'video_multi_shot',
          status: 'completed',
        },
        orderBy: { finishedAt: 'desc' },
        select: { payload: true, result: true },
      })

      // panelId → group signature lookup so we can map each task's
      // panelIds back to the group it produced.
      const panelToGroupKey = new Map<string, string>()
      for (const sig of groupSigs) {
        const sbPanels = episode.storyboards.find((sb) => sb.id === sig.storyboardId)?.panels ?? []
        for (const p of sbPanels) {
          if (p.multiShotGroupId === sig.groupId) {
            panelToGroupKey.set(p.id, `${sig.storyboardId}:${sig.groupId}`)
          }
        }
      }

      // Pick the most recent completed task per group.
      const cosByGroupKey = new Map<string, string[]>()
      for (const t of completedTasks) {
        const payloadObj = (t.payload && typeof t.payload === 'object' ? t.payload : null) as
          | { panelIds?: unknown }
          | null
        const panelIds = Array.isArray(payloadObj?.panelIds)
          ? payloadObj.panelIds.filter((x): x is string => typeof x === 'string')
          : []
        if (panelIds.length === 0) continue
        const groupKey = panelToGroupKey.get(panelIds[0])
        if (!groupKey || cosByGroupKey.has(groupKey)) continue
        const resultObj = (t.result && typeof t.result === 'object' ? t.result : null) as
          | { multiShotVideoUrl?: unknown; multiShotClipUrls?: unknown }
          | null
        // Prefer the multi-clip array (new in 2026-05-03 chunked
        // dispatch). Fall back to the legacy single string.
        const cosKeys: string[] = (() => {
          const arr = resultObj?.multiShotClipUrls
          if (Array.isArray(arr)) {
            const filtered = arr.filter(
              (k): k is string => typeof k === 'string' && k.length > 0,
            )
            if (filtered.length > 0) return filtered
          }
          return typeof resultObj?.multiShotVideoUrl === 'string'
            ? [resultObj.multiShotVideoUrl]
            : []
        })()
        if (cosKeys.length > 0) cosByGroupKey.set(groupKey, cosKeys)
      }

      groupSigs.forEach((sig, i) => {
        const cosKeys = cosByGroupKey.get(`${sig.storyboardId}:${sig.groupId}`)
        if (!cosKeys || cosKeys.length === 0) return
        // Brief note describing the group's shot range so the zip filename
        // and script.txt reader can locate it without opening the file.
        const sb = episode.storyboards.find((s) => s.id === sig.storyboardId)
        const indices = (sb?.panels ?? [])
          .filter((p) => p.multiShotGroupId === sig.groupId)
          .map((p) => p.panelIndex)
          .sort((a, b) => a - b)
        const cameraNote = indices.length > 0
          ? `panels ${indices[0]}-${indices[indices.length - 1]}`
          : null
        groupVideos.push({
          groupOrder: i + 1,
          storyboardOrder: sig.storyboardOrder,
          firstPanelIndex: sig.firstPanelIndex,
          cosKeys,
          cameraNote,
        })
      })
    }
  }

  if (panelsWithVideo.length === 0 && groupVideos.length === 0) {
    throw new Error(
      'EPISODE_PACKAGE_ZIP: no panel videos or multi-shot group videos yet — generate either before packaging',
    )
  }

  const dialogueByPanelId = new Map<string, DialogueLine[]>()
  for (const line of episode.voiceLines) {
    if (!line.matchedPanelId) continue
    const list = dialogueByPanelId.get(line.matchedPanelId) ?? []
    list.push({
      panelId: line.matchedPanelId,
      panelIndex: line.matchedPanelIndex,
      speaker: line.speaker,
      content: line.content,
      lineIndex: line.lineIndex,
    })
    dialogueByPanelId.set(line.matchedPanelId, list)
  }

  await prisma.novelPromotionEpisode.update({
    where: { id: episodeId },
    data: { stitchStatus: 'rendering' },
  })

  await reportTaskProgress(job, 10, {
    stage: 'package_assets',
    totalPanels: panelsWithVideo.length,
  })

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), `episode-pack-${episodeId}-`))
  const zipPath = path.join(tmpDir, `episode-${episodeId}.zip`)

  const archive = archiver('zip', { zlib: { level: 6 } })
  const output = fs.createWriteStream(zipPath)
  // archiveDone is awaited only on the success path. If the handler throws
  // earlier, we still attach a catch so the eventual rejection (e.g. ENOENT
  // after we rmSync tmpDir in finally) doesn't surface as an unhandled
  // rejection — the original error is what we want to propagate.
  const archiveDone = new Promise<void>((resolve, reject) => {
    output.on('close', () => resolve())
    output.on('error', (err) => reject(err))
    archive.on('error', (err) => reject(err))
  })
  archiveDone.catch(() => undefined)
  archive.pipe(output)

  try {
    archive.append(buildReadmeText(panelsWithVideo.length, groupVideos.length), { name: 'README.txt' })
    archive.append(buildScriptText(allPanels, dialogueByPanelId), { name: 'script.txt' })

    // Multi-shot group videos go into multi-shot/ alongside videos/ so
    // CapCut import keeps them on a separate track from per-panel cuts.
    //
    // Naming:
    //   - Single-clip group:  multi-shot/group01.mp4 (legacy shape)
    //   - Multi-clip group:   multi-shot/group01-clip1.mp4,
    //                         multi-shot/group01-clip2.mp4, …
    //     User imports them in numbered order; NLE auto-sequences.
    for (let i = 0; i < groupVideos.length; i++) {
      await assertTaskActive(job, 'package_assets')
      const group = groupVideos[i]
      const indexStr = String(group.groupOrder).padStart(2, '0')
      const isMultiClip = group.cosKeys.length > 1
      for (let j = 0; j < group.cosKeys.length; j++) {
        const cosKey = group.cosKeys[j]
        const url = toSignedUrlIfCos(cosKey, 7200) || cosKey
        const filename = isMultiClip
          ? `multi-shot/group${indexStr}-clip${j + 1}.mp4`
          : `multi-shot/group${indexStr}.mp4`
        try {
          const buf = await fetchToBuffer(url)
          archive.append(buf, { name: filename })
        } catch (err) {
          // Best-effort — one broken clip shouldn't kill the whole zip.
          logWarn('EPISODE_PACKAGE_ZIP: skipping multi-shot clip', {
            groupOrder: group.groupOrder,
            clipIndex: j + 1,
            totalClips: group.cosKeys.length,
            reason: (err as Error).message,
          })
        }
      }
    }

    for (let i = 0; i < panelsWithVideo.length; i++) {
      await assertTaskActive(job, 'package_assets')
      const panel = panelsWithVideo[i]
      const indexStr = String(panel.panelIndex).padStart(2, '0')
      const slug = slugifyForFilename(panel.description, `panel${indexStr}`)

      const videoUrl = toSignedUrlIfCos(panel.videoUrl, 7200) || panel.videoUrl
      if (!videoUrl) {
        throw new Error(`EPISODE_PACKAGE_ZIP: panel ${panel.id} has no resolvable video URL`)
      }
      const videoBuf = await fetchToBuffer(videoUrl)
      archive.append(videoBuf, { name: `videos/${indexStr}-${slug}.mp4` })

      if (panel.imageUrl) {
        const imageUrl = toSignedUrlIfCos(panel.imageUrl, 7200) || panel.imageUrl
        if (imageUrl) {
          try {
            const imageBuf = await fetchToBuffer(imageUrl)
            archive.append(imageBuf, { name: `images/${indexStr}-${slug}.jpg` })
          } catch (err) {
            // Image failures are non-fatal — the video is the must-have asset.
            // Log explicitly so the skip is visible in worker logs.
            logWarn('EPISODE_PACKAGE_ZIP: skipping image', {
              panelId: panel.id,
              reason: (err as Error).message,
            })
          }
        }
      }

      const progress = 10 + Math.floor(((i + 1) / panelsWithVideo.length) * 75)
      await reportTaskProgress(job, progress, {
        stage: 'package_assets',
        packed: i + 1,
        total: panelsWithVideo.length,
      })
    }

    await archive.finalize()
    await archiveDone

    await assertTaskActive(job, 'upload_zip')
    await reportTaskProgress(job, 90, { stage: 'upload_zip' })

    const zipBuffer = fs.readFileSync(zipPath)
    const cosKey = generateUniqueKey(`episode-pack-${episodeId}`, 'zip')
    await uploadToCOS(zipBuffer, cosKey)

    await assertTaskActive(job, 'persist_result')
    await reportTaskProgress(job, 97, { stage: 'persist_result' })

    await prisma.novelPromotionEpisode.update({
      where: { id: episodeId },
      data: {
        stitchedVideoUrl: cosKey,
        stitchStatus: 'completed',
        stitchedAt: new Date(),
      },
    })

    return {
      episodeId,
      outputUrl: cosKey,
      panelCount: panelsWithVideo.length,
    }
  } catch (err) {
    await prisma.novelPromotionEpisode.update({
      where: { id: episodeId },
      data: { stitchStatus: 'failed' },
    })
    throw err
  } finally {
    try {
      fs.rmSync(tmpDir, { recursive: true, force: true })
    } catch {
      // ignore cleanup errors
    }
  }
}
