/**
 * Phase 12.7.x — Episode package zip
 *
 * Replaces the old ffmpeg concat path. The platform's role ends at
 * generating per-panel videos; final cutting happens in CapCut/剪映 on
 * the user's machine. So instead of stitching 17×1080P videos into one
 * mp4 (which pegs both vCPUs for ~6 minutes and stalls BullMQ), we
 * package every panel video + storyboard image + dialogue script into
 * one zip and hand the user a download link.
 *
 * Resource profile vs. ffmpeg:
 *   - CPU: <5% (archiver is I/O bound, not encoder bound)
 *   - Time: ~30-60s for 17 panels (download + zip + upload)
 *   - Memory: peak ~600MB (full zip buffered before upload)
 *   - Heartbeat: 90s default is comfortably enough
 *
 * Output zip layout:
 *   episode-{id}.zip
 *   ├── videos/01-{slug}.mp4 ... 17-{slug}.mp4   (in panel order)
 *   ├── images/01-{slug}.jpg ... 17-{slug}.jpg   (storyboard refs)
 *   ├── script.txt                                (dialogue + camera notes)
 *   └── README.txt                                (import-to-CapCut guide)
 *
 * The output key is written to NovelPromotionEpisode.stitchedVideoUrl —
 * the column name is preserved for backward compat; semantically it now
 * holds a zip key, not an mp4 key. Frontend treats it as a download URL.
 */
import path from 'path'
import fs from 'fs'
import os from 'os'
import archiver from 'archiver'
import type { Job } from 'bullmq'
import { prisma } from '@/lib/prisma'
import type { TaskJobData } from '@/lib/task/types'
import { reportTaskProgress } from '../shared'
import { assertTaskActive, toSignedUrlIfCos } from '../utils'
import { uploadToCOS, generateUniqueKey } from '@/lib/cos'
import { logWarn } from '@/lib/logging/core'

interface PackagePayload {
  episodeId?: string
}

interface PanelForZip {
  id: string
  panelIndex: number
  description: string | null
  imageUrl: string | null
  videoUrl: string | null
  cameraMove: string | null
  shotType: string | null
}

interface DialogueLine {
  panelId: string | null
  panelIndex: number | null
  speaker: string
  content: string
  lineIndex: number
}

const FETCH_TIMEOUT_MS = 60_000

function slugifyForFilename(input: string | null, fallback: string): string {
  const base = (input ?? '').slice(0, 30).replace(/[\\/:*?"<>|\s]+/g, '_').replace(/^_+|_+$/g, '')
  return base.length > 0 ? base : fallback
}

async function fetchToBuffer(url: string): Promise<Buffer> {
  const res = await fetch(url, { signal: AbortSignal.timeout(FETCH_TIMEOUT_MS) })
  if (!res.ok) {
    throw new Error(`HTTP ${res.status} fetching ${url.slice(0, 80)}`)
  }
  return Buffer.from(await res.arrayBuffer())
}

function buildScriptText(panels: PanelForZip[], dialogueByPanelId: Map<string, DialogueLine[]>): string {
  const lines: string[] = ['EPISODE SCRIPT', '', '']
  for (const panel of panels) {
    const indexStr = String(panel.panelIndex).padStart(2, '0')
    lines.push(`--- Panel ${indexStr} ---`)
    if (panel.shotType) lines.push(`Shot: ${panel.shotType}`)
    if (panel.cameraMove) lines.push(`Camera: ${panel.cameraMove}`)
    if (panel.description) lines.push(`Scene: ${panel.description}`)
    const dialogues = dialogueByPanelId.get(panel.id) ?? []
    if (dialogues.length > 0) {
      lines.push('')
      for (const d of dialogues) {
        lines.push(`  ${d.speaker}: ${d.content}`)
      }
    }
    lines.push('', '')
  }
  return lines.join('\n')
}

function buildReadmeText(panelCount: number): string {
  return [
    'KuiperAI Episode Package',
    '========================',
    '',
    `This zip contains ${panelCount} panel videos plus storyboard images and a dialogue script.`,
    '',
    'Folder layout:',
    '  videos/    — per-panel mp4, named in scene order (01, 02, ...)',
    '  images/    — storyboard reference images for each panel',
    '  script.txt — dialogue + camera notes per panel',
    '',
    'Import workflow (CapCut / 剪映):',
    '  1. Drag the entire videos/ folder into your project.',
    '  2. Files are pre-numbered, so they sort correctly on the timeline.',
    '  3. Use script.txt as a reference for cuts, captions, and voiceover.',
    '',
    'Generated by KuiperAI.',
    '',
  ].join('\n')
}

export async function handleEpisodePackageZipTask(job: Job<TaskJobData>) {
  const payload = (job.data.payload || {}) as PackagePayload
  const episodeId = typeof payload.episodeId === 'string' ? payload.episodeId : ''
  if (!episodeId) {
    throw new Error('EPISODE_PACKAGE_ZIP: missing episodeId in payload')
  }

  await reportTaskProgress(job, 5, { stage: 'load_panels' })
  await assertTaskActive(job, 'load_panels')

  const episode = await prisma.novelPromotionEpisode.findUnique({
    where: { id: episodeId },
    include: {
      storyboards: {
        include: {
          panels: { orderBy: { panelIndex: 'asc' } },
        },
        orderBy: { createdAt: 'asc' },
      },
      voiceLines: { orderBy: { lineIndex: 'asc' } },
    },
  })
  if (!episode) {
    throw new Error(`EPISODE_PACKAGE_ZIP: episode not found: ${episodeId}`)
  }

  const allPanels: PanelForZip[] = episode.storyboards.flatMap((sb) =>
    sb.panels.map((p) => ({
      id: p.id,
      panelIndex: p.panelIndex,
      description: p.description,
      imageUrl: p.imageUrl,
      videoUrl: p.videoUrl,
      cameraMove: p.cameraMove,
      shotType: p.shotType,
    })),
  )
  const panelsWithVideo = allPanels.filter((p) => Boolean(p.videoUrl))
  if (panelsWithVideo.length === 0) {
    throw new Error('EPISODE_PACKAGE_ZIP: no panels have videoUrl yet — generate panel videos first')
  }

  const dialogueByPanelId = new Map<string, DialogueLine[]>()
  for (const line of episode.voiceLines) {
    if (!line.matchedPanelId) continue
    const list = dialogueByPanelId.get(line.matchedPanelId) ?? []
    list.push({
      panelId: line.matchedPanelId,
      panelIndex: line.matchedPanelIndex,
      speaker: line.speaker,
      content: line.content,
      lineIndex: line.lineIndex,
    })
    dialogueByPanelId.set(line.matchedPanelId, list)
  }

  await prisma.novelPromotionEpisode.update({
    where: { id: episodeId },
    data: { stitchStatus: 'rendering' },
  })

  await reportTaskProgress(job, 10, {
    stage: 'package_assets',
    totalPanels: panelsWithVideo.length,
  })

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), `episode-pack-${episodeId}-`))
  const zipPath = path.join(tmpDir, `episode-${episodeId}.zip`)

  const archive = archiver('zip', { zlib: { level: 6 } })
  const output = fs.createWriteStream(zipPath)
  // archiveDone is awaited only on the success path. If the handler throws
  // earlier, we still attach a catch so the eventual rejection (e.g. ENOENT
  // after we rmSync tmpDir in finally) doesn't surface as an unhandled
  // rejection — the original error is what we want to propagate.
  const archiveDone = new Promise<void>((resolve, reject) => {
    output.on('close', () => resolve())
    output.on('error', (err) => reject(err))
    archive.on('error', (err) => reject(err))
  })
  archiveDone.catch(() => undefined)
  archive.pipe(output)

  try {
    archive.append(buildReadmeText(panelsWithVideo.length), { name: 'README.txt' })
    archive.append(buildScriptText(allPanels, dialogueByPanelId), { name: 'script.txt' })

    for (let i = 0; i < panelsWithVideo.length; i++) {
      await assertTaskActive(job, 'package_assets')
      const panel = panelsWithVideo[i]
      const indexStr = String(panel.panelIndex).padStart(2, '0')
      const slug = slugifyForFilename(panel.description, `panel${indexStr}`)

      const videoUrl = toSignedUrlIfCos(panel.videoUrl, 7200) || panel.videoUrl
      if (!videoUrl) {
        throw new Error(`EPISODE_PACKAGE_ZIP: panel ${panel.id} has no resolvable video URL`)
      }
      const videoBuf = await fetchToBuffer(videoUrl)
      archive.append(videoBuf, { name: `videos/${indexStr}-${slug}.mp4` })

      if (panel.imageUrl) {
        const imageUrl = toSignedUrlIfCos(panel.imageUrl, 7200) || panel.imageUrl
        if (imageUrl) {
          try {
            const imageBuf = await fetchToBuffer(imageUrl)
            archive.append(imageBuf, { name: `images/${indexStr}-${slug}.jpg` })
          } catch (err) {
            // Image failures are non-fatal — the video is the must-have asset.
            // Log explicitly so the skip is visible in worker logs.
            logWarn('EPISODE_PACKAGE_ZIP: skipping image', {
              panelId: panel.id,
              reason: (err as Error).message,
            })
          }
        }
      }

      const progress = 10 + Math.floor(((i + 1) / panelsWithVideo.length) * 75)
      await reportTaskProgress(job, progress, {
        stage: 'package_assets',
        packed: i + 1,
        total: panelsWithVideo.length,
      })
    }

    await archive.finalize()
    await archiveDone

    await assertTaskActive(job, 'upload_zip')
    await reportTaskProgress(job, 90, { stage: 'upload_zip' })

    const zipBuffer = fs.readFileSync(zipPath)
    const cosKey = generateUniqueKey(`episode-pack-${episodeId}`, 'zip')
    await uploadToCOS(zipBuffer, cosKey)

    await assertTaskActive(job, 'persist_result')
    await reportTaskProgress(job, 97, { stage: 'persist_result' })

    await prisma.novelPromotionEpisode.update({
      where: { id: episodeId },
      data: {
        stitchedVideoUrl: cosKey,
        stitchStatus: 'completed',
        stitchedAt: new Date(),
      },
    })

    return {
      episodeId,
      outputUrl: cosKey,
      panelCount: panelsWithVideo.length,
    }
  } catch (err) {
    await prisma.novelPromotionEpisode.update({
      where: { id: episodeId },
      data: { stitchStatus: 'failed' },
    })
    throw err
  } finally {
    try {
      fs.rmSync(tmpDir, { recursive: true, force: true })
    } catch {
      // ignore cleanup errors
    }
  }
}
